/* CLUSTERING FIGURES - ESTIMATED QUERY RUN TIME IS 4min30 */

SELECT CAST ('INDIVIDUALS - NO. OF PARTIES' AS VARCHAR (100) ) AS TBL,
COUNT (*) (INTEGER) AS COUNT_NUM FROM EDW_SCVER_CODA_ACCS_VIEWS.V_INDIVIDUAL I
WHERE  (I.FORENAME IS NOT NULL OR I.LASTNAME IS NOT NULL) 
AND NOT (I.FORENAME IS NULL AND I.LASTNAME = 'UNKNOWN')
AND NOT (I.FORENAME ='UNKNOWN' AND I.LASTNAME = 'UNKNOWN')
AND  I.INDIV_CLUSTER_ID IS NOT NULL

UNION

SELECT CAST ('INDIVIDUALS - NO. OF CLUSTERS' AS VARCHAR (100) ) AS TBL, SUM (C) AS COUNT_NUM FROM
(SELECT DA.ADDRESS_GRPNG_KEY, COUNT (DISTINCT I.INDIV_CLUSTER_ID) AS C 
FROM EDW_SCVER_CODA_ACCS_VIEWS.V_INDIVIDUAL I
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_PARTY_ADDRESS PA
ON I.PARTY_ID = PA.PARTY_ID
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_DIM_ADDRESS DA
ON PA.ADDRESS_ID = DA.ADDRESS_ID
WHERE  DA.ADDRESS_GRPNG_KEY  IS NOT NULL
AND  (I.FORENAME IS NOT NULL OR I.LASTNAME IS NOT NULL) 
AND NOT (I.FORENAME IS NULL AND I.LASTNAME = 'UNKNOWN')
AND NOT (I.FORENAME ='UNKNOWN' AND I.LASTNAME = 'UNKNOWN')
AND  I.INDIV_CLUSTER_ID IS NOT NULL
GROUP BY DA.ADDRESS_GRPNG_KEY HAVING C >=1
) AS TEMP

UNION

SELECT CAST ('INDIVIDUALS - NO. OF CLUSTERS WITH > 1' AS VARCHAR (100) ) AS TBL, COUNT (NUM) AS COUNT_NUM FROM(
SELECT DA.ADDRESS_GRPNG_KEY, I.INDIV_CLUSTER_ID, COUNT(*) AS NUM
FROM EDW_SCVER_CODA_ACCS_VIEWS.V_INDIVIDUAL I
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_PARTY_ADDRESS PA
ON I.PARTY_ID = PA.PARTY_ID
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_DIM_ADDRESS DA
ON PA.ADDRESS_ID = DA.ADDRESS_ID
WHERE  DA.ADDRESS_GRPNG_KEY  IS NOT NULL
AND  (I.FORENAME IS NOT NULL OR I.LASTNAME IS NOT NULL) 
AND NOT (I.FORENAME IS NULL AND I.LASTNAME = 'UNKNOWN')
AND NOT (I.FORENAME ='UNKNOWN' AND I.LASTNAME = 'UNKNOWN')
AND  I.INDIV_CLUSTER_ID IS NOT NULL
GROUP BY DA.ADDRESS_GRPNG_KEY, I.INDIV_CLUSTER_ID
HAVING NUM > 1) AS TEMP

UNION

SELECT CAST ('ORGANIZATIONS - NO. OF PARTIES' AS VARCHAR (100) ) AS TBL,
COUNT (*) (INTEGER) AS COUNT_NUM FROM EDW_SCVER_CODA_ACCS_VIEWS.V_ORGANIZATION I
WHERE  
I.ORGANIZATION_NAME IS NOT NULL 
AND NOT (I.ORGANIZATION_NAME ='UNKNOWN')
;


/* CLUSTERING FIGURES BUSINESSES - THESE DO NOT WORK AS ORGANIZATION_CLUSTER_ID ARE NULL  

UNION

SELECT CAST ('ORGANIZATIONS - NO. OF PARTIES' AS VARCHAR (100) ) AS TBL,
COUNT (*) (INTEGER) AS COUNT_NUM FROM EDW_SCVER_CODA_ACCS_VIEWS.V_ORGANIZATION I
WHERE  
I.ORGANIZATION_NAME IS NOT NULL 
AND NOT (I.ORGANIZATION_NAME ='UNKNOWN')


UNION

SELECT CAST ('ORGANIZATIONS - NO. OF CLUSTERS' AS VARCHAR (100) ) AS TBL, SUM (C) AS COUNT_NUM FROM
(SELECT DA.ADDRESS_GRPNG_KEY, COUNT (*) AS C 
FROM EDW_SCVER_CODA_ACCS_VIEWS.V_ORGANIZATION I
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_PARTY_ADDRESS PA
ON I.PARTY_ID = PA.PARTY_ID
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_DIM_ADDRESS DA
ON PA.ADDRESS_ID = DA.ADDRESS_ID
WHERE  DA.ADDRESS_GRPNG_KEY  IS NOT NULL
AND  (I.ORGANIZATION_NAME IS NOT NULL) 
AND NOT (I.ORGANIZATION_NAME ='UNKNOWN')
GROUP BY DA.ADDRESS_GRPNG_KEY HAVING C >=1
) AS TEMP

UNION

SELECT CAST ('ORGANIZATIONS - NO. OF CLUSTERS WITH > 1' AS VARCHAR (100) ) AS TBL, COUNT (NUM) AS COUNT_NUM FROM(
SELECT DA.ADDRESS_GRPNG_KEY,  COUNT(*) AS NUM
FROM EDW_SCVER_CODA_ACCS_VIEWS.V_ORGANIZATION I
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_PARTY_ADDRESS PA
ON I.PARTY_ID = PA.PARTY_ID
LEFT OUTER JOIN EDW_SCVER_CODA_ACCS_VIEWS.V_DIM_ADDRESS DA
ON PA.ADDRESS_ID = DA.ADDRESS_ID
WHERE  DA.ADDRESS_GRPNG_KEY  IS NOT NULL
AND  (I.ORGANIZATION_NAME IS NOT NULL) 
AND NOT (I.ORGANIZATION_NAME ='UNKNOWN')
GROUP BY DA.ADDRESS_GRPNG_KEY
HAVING NUM > 1) AS TEMP;


sel top 10 * from edw_scver_coda_accs_views.v_dim_address
where tho_thoroughfare = 'VICTORIA EMBANKMENT'
and prem_buildingnumber = 100
and current_record_ind = 1
;



select count (distinct party_id) from
EDW_SCVER_CODA_ACCS_VIEWS.V_PARTY_ADDRESS PA
where PA.ADDRESS_ID IN (
335031253,
333044331,
333637859,
332635849
);


*/

/*
select p.party_id, p.party_desc, pa.address_id, da.*  from
EDW_SCVER_CODA_ACCS_VIEWS.V_PARTY_ADDRESS PA
inner join edw_scver_coda_accs_views.v_party P
ON P.party_id = PA.party_id
and PA.address_type_id = 1
AND PA.ADDRESS_ID IN (335031253,333044331,333637859,332635849)
INNER JOIN edw_scver_coda_dim_views.v_dim_address DA
ON DA.ADDRESS_ID = PA.ADDRESS_ID;

sel top 10 * from edw_scver_coda_accs_views.v_party;
*/
